version: 2

models:
  - name: stg_clean_trips
    columns:
      - name: pickup_datetime
        tests:
          - not_null
      - name: dropoff_datetime
        tests:
          - not_null
      - name: trip_distance
        tests:
          - not_null
      - name: total_amount
        tests:
          - not_null

  - name: ml_features
    columns:
      - name: total_amount
        tests:
          - not_null
      - name: trip_distance
        tests:
          - not_null
      - name: trip_duration_minutes
        tests:
          - not_null
